language: c
os:
  - osx
  - linux
compiler:
  - gcc
  - clang
env:
  - EXTRA=libpcsclite-dev
script:
  - ./build-and-test.sh
matrix:
  include:
    - compiler: gcc
      os: linux
      env: EXTRA="wine mingw-w64 mingw-w64-i686-dev" REMOVE=mingw32 ARCH=32
    - compiler: gcc
      os: linux
      env: EXTRA="wine mingw-w64 mingw-w64-x86-64-dev" REMOVE=mingw32 ARCH=64
    - compiler: gcc
      os: linux
      env: COVERAGE="--enable-coverage" EXTRA="libpcsclite-dev lcov"
    - compiler: gcc
      os: linux
      env: BUILD_OPENSSL_VERSION="1.1" EXTRA="libpcsclite-dev"
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Ben Babik (auto)"
  - git config --local user.email "work@benjaminbabik.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: ./*.zip
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    all_branches: true

